# Neural Network

colab에서 열기: 

## Tensor

In [2]:
import torch #pytorch: 머신러닝 라이브러리

In [8]:
#tensor: 배열의 집합
# x = torch.Tensor(행, 열)
x = torch.Tensor(2, 3)
print(x)

tensor([[1.7156e-07, 1.7662e-04, 2.5643e-09],
        [2.1456e-07, 1.7474e-04, 1.3662e-05]])


In [10]:
a = torch.zeros(2, 3)#0으로 채워진 Tensor 선언
b = torch.ones(2, 3)#1로 채워진 Tensor 선언
c = torch.rand(2, 3)#0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
d = torch.randn(2, 3)#평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
e = torch.eye(2, 3)#정방행렬과 같은 Tensor 선언
f = torch.arange(0, 2, step=0.5)#0부터 2까지 0.5씩 증가하는 Tensor 선언
g = torch.Tensor([[1,2,3],[1,2,3]])#직접 값을 입력하여 선언
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor and Numpy

In [22]:
import numpy as np

In [23]:
#numpy 형식의 배열
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [26]:
#numpy를 tensor로 변환
x = torch.from_numpy(x) # x = torch.Tensor(x)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1, 2, 3],
        [1, 2, 3]])
Tensor Type :  torch.LongTensor
Tensor Size :  torch.Size([2, 3])


In [27]:
#tensor를 numpy로 변환
x = x.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## Tensor Slicing

In [28]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [29]:
#모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [30]:
#2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [31]:
#2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [33]:
#1행 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [34]:
#x를 1행씩 잘라서 배열로 저장
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [35]:
#x를 2열씩 잘라서 배열로 저장
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [40]:
#x_cols의 첫번째 배열 중 특정 부분만 추출하기
torch.masked_select(x_cols[0], torch.Tensor([[0,1],[1,0],[0,1]]).bool())

tensor([ 2.,  5., 10.])

##  Tensor Merging

In [29]:
#x_rows를 행으로 이어 붙이기
torch.cat(x_rows, dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [30]:
#x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [31]:
#x_cols를 쌓아올리기
x_new = torch.stack(x_cols, dim=0)
print(x_new)#쌓아 올리는거, shape같아야 함.

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])


## Tensor Reshaping

In [32]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [33]:
#4행 3열로 바꾸기
x.view(4, 3)#reshape와 같은 역할

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [34]:
#2열로 바꾸기
x.view(-1, 2)#-1: 알맞은 숫자로 reshape해줌 (3,4) ->(6,2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [35]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [36]:
#차원이 1인 값을 축소
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [37]:
#dim=1 자리에 차원을 추가
x.view(2, 1, -1).squeeze().unsqueeze(dim=1)#sq 차원 1인애 없애라unsq 차원 추가해라

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

## Tensor Calculation

In [38]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [39]:
# x와 y의 합
z = torch.add(x, y)
print("z :", z)
print("x+y :", x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x+y : tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [40]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [41]:
#x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
x*y : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [42]:
#x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
x**2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [43]:
#x의 원소에 log를 씌움
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log() : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [44]:
#x의 원소에 루트를 씌움
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [45]:
#x의 원소에 나머지(mod) 계산
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [46]:
#x에 절댓값
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[1., 2., 3.],
        [4., 5., 6.]])
x.abs() : tensor([[1., 2., 3.],
        [4., 5., 6.]])


numpy와 비슷한 문법을 사용함.